---
# handlers file for pterodactyl_panel
- name: restart queue service
  systemd:
    name: pteroq.service
    state: restarted

- name: restart schedule service
  systemd:
    name: pterosched.service
    state: restarted

- name: restart apache2
  systemd:
    name: apache2
    state: restarted
